Updates the git-extras comamnds I use

diff --git a/bin/git-delete-branch b/bin/git-delete-branch
--- a/bin/git-delete-branch
+++ b/bin/git-delete-branch
@@ -1,7 +1,16 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-branch=$1
-test -z $branch && echo "branch required." 1>&2 && exit 1
-git branch -D $branch
-git branch -d -r origin/$branch
-git push origin :refs/heads/$branch
+# Assert there is at least one branch provided
+test -z $1 && echo "branch required." 1>&2 && exit 1
+
+for branch in "$@"
+do
+  remote=$(git config branch.$branch.remote)
+  test -z $remote && remote="origin"
+  ref=$(git config branch.$branch.merge)
+  test -z $ref && ref="refs/heads/$branch"
+
+  git branch -D $branch
+  git branch -d -r $remote/$branch
+  git push $remote :$ref
+done
diff --git a/bin/git-graft b/bin/git-graft
--- a/bin/git-graft
+++ b/bin/git-graft
@@ -1,8 +1,9 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-test -z $1 && echo "source branch required." && exit 1
 src=$1
-dst=${2-master}
+dst=$2
+
+test -z $src && echo "source branch required." 1>&2 && exit 1
 
 git checkout $dst \
   && git merge --no-ff $src \
